name = "pretty-website"
main = "src/index.js"  # Entry point for your Worker script

[site]
bucket = "./public"  # Directory containing your static files (HTML, CSS, JS)

# Optional: Add environment variables or secrets
[vars]
WEBSOCKET_URL = "wss://AcclaimedDeadSpof.darshanisadev.repl.co"

[observability.logs]
enabled = true

