name = "pretty-website"  # Name of your Worker
main = "src/index.js"       # Entry point for your Worker script
compatibility_date = "2023-10-01"  # Compatibility date for Cloudflare Workers

# Configuration for serving static files
[site]
bucket = "./public"  # Directory containing your static files (HTML, CSS, JS)

# Define triggers (optional)
[triggers]
crons = []  # Add cron jobs if needed
