name = "pretty-website"
main = "src/index.js"
compatibility_date = "2023-10-01"

[site]
bucket = "./public"  # Directory containing your static files (HTML, CSS, JS)
entry-point = "src"  # Entry point for your Worker script

# Optional: Add environment variables or secrets
[vars]
WEBSOCKET_URL = "wss://AcclaimedDeadSpof.darshanisadev.repl.co"
